# Simple Azure deployment workflow
name: Deploy Backend to Azure

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: Backend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd Backend
        npm ci --only=production
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1E046F185D55447F80E8476E16F3595D }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D12D92930B12450CAA9D2DA86C4E8533 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BFBA908AF0A340599980D8800EC864D5 }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'social-sphere'
        package: Backend

    - name: Health Check
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30
        curl -f https://social-sphere.azurewebsites.net/ || echo "Health check failed, but deployment completed"
